budget/urls.py
from django.urls import path

from . import views

app_name = 'budget'
urlpatterns = [
    path('', views.index, name='index'),
    path('edit_execution/<int:execution_id>/', views.edit_execution, name='edit_execution'),
    path('budget_execution/', views.budget_execution, name='budget_execution'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

data_visualization/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django_registration.backends.one_step.views import RegistrationView
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^accounts/register/',
        RegistrationView.as_view(success_url='/budget/'),
        name='django_registration_register'),
    url(r'^accounts/', include('django_registration.backends.one_step.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    path('budget/', include('budget.urls')),
    path('admin/', admin.site.urls, ),
    url('', RedirectView.as_view(url='/budget/', permanent=False), name='index'),
]

budget/models.py
from django.db import models
from django.urls import reverse

class Unit(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name
    def natural_key(self):
        return (self.id, self.name)

class Indicator(models.Model):
    name = models.CharField(max_length=255)
    kbk = models.CharField(max_length=100)
    def __str__(self):
        return self.kbk + ' - ' + self.name
    def natural_key(self):
        return (self.id, self.kbk, self.name)

class Execution(models.Model):
    year = models.IntegerField()
    purpose = models.FloatField()
    cash = models.FloatField()
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    indicator = models.ForeignKey(Indicator, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.year) + ': ' + self.indicator.name

budget/views.py
import json

from django.shortcuts import get_object_or_404, render, redirect
from django.http import JsonResponse, HttpResponseRedirect
from django.core.exceptions import PermissionDenied
from django.core import serializers
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout

from .models import Execution

def index(request):
    return render(request, 'budget/index.html')

def edit_execution(request, execution_id):
    if not request.user.is_authenticated:
        raise PermissionDenied

    execution = get_object_or_404(Execution, pk=execution_id)

    if request.method == 'POST':
        purpose = float(request.POST.get('purpose', execution.purpose))
        cash = float(request.POST.get('cash', execution.cash))
        execution.cash = cash
        execution.purpose = purpose
        execution.save()

    response_data = json.loads(serializers.serialize('json', [ execution, ], indent=2, use_natural_foreign_keys=True, use_natural_primary_keys=True))
    return JsonResponse(response_data[0])

def budget_execution(request):
    draw = int(request.GET.get('draw', 1))
    start = int(request.GET.get('start', 0))
    length = int(request.GET.get('length', 10))
    search = str(request.GET.get('search[value]', ''))
    order_column = request.GET.get('order[0][column]', '2')
    order_dir = request.GET.get('order[0][dir]', 'asc')
    column_name = request.GET.get('columns[' + order_column + '][name]', '')

    objects = Execution.objects

    records_total = objects.count()

    objects_filtered = objects.all()

    if (len(column_name) > 0):
        desc = ''
        if (order_dir == 'desc'):
            desc = '-'
        objects_filtered = objects_filtered.order_by(desc + column_name)

    if (len(search) > 3):
        objects_filtered = objects_filtered.filter(Q(year__icontains=search) | Q(indicator__kbk__icontains=search) | Q(indicator__name__icontains=search))

    records_filtered = objects_filtered.count()

    paginator = Paginator(objects_filtered, length)
    page = start / length + 1
    if (page <= 0):
        page = 1
    object_list = paginator.page(page)

    data = json.loads(serializers.serialize('json', object_list, indent=2, use_natural_foreign_keys=True, use_natural_primary_keys=True))

    response_data = {}
    response_data['column_name'] = column_name
    response_data['draw'] = draw
    response_data['recordsTotal'] = records_total
    response_data['recordsFiltered'] = records_filtered
    response_data['data'] = data

    return JsonResponse(response_data)

def login_view(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
    return redirect('budget:index')

def logout_view(request):
    logout(request)
    return redirect('budget:index')

budget/templates/budget/index.html
{% extends './layout.html' %}
{% block content %}
<div class="alert alert-warning js-charts-warning" role="alert" style="display:none">Необходимо выбрать КБК для отображения графиков</div>

<div class="row js-charts">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Первый чарт</h3>
            </div>
            <div class="panel-body">
                <div id="primary_chart" style="height: 400px;"></div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Второй чарт</h3>
            </div>
            <div class="panel-body">
                <div id="secondary_chart" style="height: 400px;"></div>
            </div>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Табличные данные</h3>
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped" id="budgetExecution">
                <thead>
                    <tr>
                        <th><i class="fa fa-pencil-alt"></i></th>
                        <th>Год</th>
                        <th>КБК</th>
                        <th>Наименование показателя</th>
                        <th>Назначение</th>
                        <th>Исполнение</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>
</div>
{% if user.is_authenticated %}
<div class="modal fade" tabindex="-1" role="dialog" id="editExecution">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Редактирование показателя</h4>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="col-md-3 control-label">Год</label>
                        <div class="col-md-9">
                            <p class="form-control-static js-execution-year"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">КБК</label>
                        <div class="col-md-9">
                            <p class="form-control-static js-execution-kbk"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Наименование показателя</label>
                        <div class="col-md-9">
                            <p class="form-control-static js-execution-indicator"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Назначение</label>
                        <div class="col-md-9">
                            <div class="input-group">
                                <input class="form-control text-right js-execution-purpose" type="text" name="execution_purpose" value="">
                                <span class="input-group-addon">₽</span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Исполнение</label>
                        <div class="col-md-9">
                            <div class="input-group">
                                <input class="form-control text-right js-execution-cash" type="text" name="execution_cash" value="">
                                <span class="input-group-addon">₽</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                {% csrf_token %}
                <input class="js-execution-id" type="hidden" value="">
                <button type="button" class="btn btn-primary js-save-execution">Сохранить</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

budget/templates/budget/layout.html
{% load static %}
<!doctype html>
<html lang="ru">
    <head>
        <title>Информация об исполнении областного бюджета</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'budget/main.css' %}?v=4">
        <script>
            var is_authenticated = {{ user.is_authenticated|yesno:"true,false" }};
        </script>
    </head>
    <body>
        <div class="wrap">
            <nav class="navbar navbar-default header">
                <div class="container">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="{% url 'budget:index' %}">Информация об исполнении областного бюджета</a>
                    </div>

                    <div class="collapse navbar-collapse" id="profileMenu">
                        <ul class="nav navbar-nav navbar-right">
                            {% if user.is_authenticated %}
                                <li><a href="{% url 'budget:logout' %}">Выход ({{ user.username }})</a></li>
                            {% else %}
                                <li><a href="#" data-toggle="modal" data-target="#auth">Войти</a></li>
                                <li><a href="{% url 'django_registration_register' %}">Зарегистрироваться</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="content container">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <footer class="footer">
            &copy; Кожеко И.М., 2018 / Powered by Django
        </footer>

        <div id="auth" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <form class="modal-content" method="post" action="{% url 'budget:login' %}">
                    {% csrf_token %}
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Вход</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label>Имя пользователя</label>
                            <input name="username" type="text" class="form-control" placeholder="Введите имя пользователя">
                        </div>
                        <div class="form-group">
                            <label>Пароль</label>
                            <input name="password" type="password" class="form-control" placeholder="Введите пароль">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Войти</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    </div>
                </form>
          </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
        <script src="{% static 'budget/main.js' %}?v=7"></script>
        <script src="{% static 'budget/echarts.min.js' %}"></script>
    </body>
</html>

budget/templates/django_registration/registration_form.html
{% extends './../budget/layout.html' %}
{% load add_class %}
{% block content %}
<div class="form-center">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Регистрация пользователя</h2>
        </div>
        <div class="panel-body">
            <form method="post" action="{% url 'django_registration_register' %}">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group {% if field.errors %}has-error{% endif %}">
                        {{ field.label_tag }}
                        {{ field|add_class:'form-control' }}
                        {% if field.help_text %}<p class="help-block">{{ field.help_text|safe }}</p>{% endif %}
                        {% if field.errors %}<p class="help-block">{{ field.errors }}</p>{% endif %}
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-default">Зарегистрироваться</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}